### ISSUE TITLE
Cellery command to get current namespace

### ISSUE THREAD

**Issue by hasinthaindrajee** [wso2/cellery#1027] opened 2019-12-17 03:46 UTC
**Description:**
I think it would be convenient if we had a command to get the current namespace which is acting as the default namespace. 

If we have a kubectl command that should also be sufficient.

Also it would be nice if we can validate whether the name space is available before setting it as namespace through cellery. I had to face an issue where the namespace is getting set without any errors with a typo and failed to deploy cell due to non existing ns. We can do this improvement as a future improvement.

**Comment by MadhukaHarith92** [comment] 2019-12-17 04:30
+1 for the suggestion. In addition, I think it would be better if the already existing `cellery set namespace` command got modified. IMO `namespace` should be a parent command.

This way there would be 2 commands.
1. `cellery namespace current` to get the current namespace.
2. `cellery namespace update` to modify the namespace.

**Comment by MadhukaHarith92** [comment] 2019-12-18 14:02
The second part of the issue is resolved by https://github.com/wso2/cellery/pull/1059

**Comment by MadhukaHarith92** [comment] 2019-12-18 14:06
We can get the current namespace by executing the kubeclt command `kubectl config view | grep namespace`. However, we can introduce a cellery command in future to get this result.

**Closed** 2021-02-05 07:33 UTC
Labels: Resolution/Won’t Fix, Type/New Feature, component/CLI
